<?php

declare(strict_types=1);

namespace eseperio\verifactu\models;

/**
 * Model representing the response to an invoice submission or cancellation.
 * Based on: RespuestaRegFactuSistemaFacturacionType (RespuestaSuministro.xsd.xml).
 */
class InvoiceResponse extends Model
{
    public const STATUS_OK = 'Correcto';

    /**
     * CSV generated by AEAT (only if there is no rejection).
     * Property: CSV
     * @var string
     */
    public $csv;

    /**
     * Submission data (DatosPresentacion, optional).
     * Property: DatosPresentacion
     * @var array
     */
    public $submissionData;

    /**
     * Submission header (Cabecera).
     * Property: Cabecera
     * @var array
     */
    public $header;

    /**
     * Wait time for the next submission (TiempoEsperaEnvio).
     * Property: TiempoEsperaEnvio
     * @var string
     */
    public $waitTime;

    /**
     * Global status of the submission (EstadoEnvio).
     * Property: EstadoEnvio
     * @var string
     */
    public $submissionStatus;

    /**
     * Detailed line responses (RespuestaLinea, optional).
     */
    public $lineResponses;

    /**
     * Returns validation rules for invoice response.
     */
    public function rules(): array
    {
        return [
            [['header', 'waitTime', 'submissionStatus'], 'required'],
            [['csv', 'waitTime', 'submissionStatus'], 'string'],
            [['submissionData', 'header', 'lineResponses'], 'array'],
        ];
    }

    /**
     * Returns an associative array of error codes and error descriptions
     * from all line responses that contain errors.
     *
     * @return array<string, string>
     */
    public function getErrors(): array
    {
        $errors = [];
        if (!is_array($this->lineResponses)) {
            return $errors;
        }
        foreach ($this->lineResponses as $line) {
            if (
                isset($line['CodigoErrorRegistro']) &&
                $line['CodigoErrorRegistro'] !== null &&
                $line['CodigoErrorRegistro'] !== '' &&
                isset($line['DescripcionErrorRegistro']) &&
                $line['DescripcionErrorRegistro'] !== null &&
                $line['DescripcionErrorRegistro'] !== ''
            ) {
                $errors[(string)$line['CodigoErrorRegistro']] = (string)$line['DescripcionErrorRegistro'];
            }
        }
        return $errors;
    }
}
