<?php
namespace eseperio\verifactu\models;

/**
 * Model representing the response to an invoice submission or cancellation.
 * Based on: RespuestaRegFactuSistemaFacturacionType (RespuestaSuministro.xsd.xml)
 */
class InvoiceResponse extends Model
{

    const STATUS_OK = 'Correcto';

    /**
     * CSV generated by AEAT (only if not rejected)
     * @var string
     */
    public $csv;

    /**
     * Submission details (DatosPresentacion, optional)
     * @var array
     */
    public $submissionData;

    /**
     * Header data (Cabecera)
     * @var array
     */
    public $header;

    /**
     * Wait time for next submission (TiempoEsperaEnvio)
     * @var string
     */
    public $waitTime;

    /**
     * Overall status of the submission (EstadoEnvio)
     * @var string
     */
    public $submissionStatus;

    /**
     * Detailed response for each line submitted (RespuestaLinea, optional)
     * @var array
     */
    public $lineResponses;

    /**
     * Returns validation rules for invoice response.
     * @return array
     */
    public function rules()
    {
        return [
            [['header', 'waitTime', 'submissionStatus'], 'required'],
            [['csv', 'waitTime', 'submissionStatus'], 'string'],
            [['submissionData', 'header', 'lineResponses'], 'array'],
        ];
    }
}
